---
# openbsd-nginx: nginx on OpenBSD with vhost for ldapcherry (self-signed SSL)

nginx_config_dir: "/etc/nginx"
nginx_ssl_base_dir: "{{ nginx_config_dir }}/ssl"
nginx_vhosts_include: "{{ nginx_config_dir }}/vhosts.conf"

# --- LdapCherry vhost ---
nginx_ldapcherry_enable: true
nginx_ldapcherry_server_name: "ldap.int.kakwalab.ovh"
nginx_ldapcherry_backend: "127.0.0.1:8080"
nginx_ldapcherry_ssl_dir: "{{ nginx_ssl_base_dir }}/ldapcherry"
nginx_ldapcherry_ssl_cert: "{{ nginx_ldapcherry_ssl_dir }}/cert.pem"
nginx_ldapcherry_ssl_key: "{{ nginx_ldapcherry_ssl_dir }}/key.pem"
nginx_ldapcherry_ssl_cn: "{{ nginx_ldapcherry_server_name }}"
nginx_ldapcherry_ssl_valid_days: 3650
