---
- name: Reload nsd
  ansible.builtin.service:
    name: nsd
    state: reloaded
  when: ansible_facts.os_family == "OpenBSD"

- name: Restart DnsCherry
  ansible.builtin.service:
    name: dnscherry
    state: restarted
  when: ansible_facts.os_family == "OpenBSD"
