---
- name: Reload nsd
  ansible.builtin.command:
    cmd: "nsd-control rebuild && nsd-control reload"
  when: ansible_facts.os_family == "OpenBSD"

- name: Restart DnsCherry
  ansible.builtin.service:
    name: dnscherry
    state: restarted
  when: ansible_facts.os_family == "OpenBSD"
